apiVersion: v1
kind: Secret
metadata:
  name: hatchet-stack-databases
type: Opaque
data:
  {{- if .Values.postgres.enabled }}
  DATABASE_POSTGRES_HOST: {{ printf "%s-postgres" .Release.Name | b64enc }}
  DATABASE_POSTGRES_USERNAME: {{ .Values.postgres.auth.username | b64enc }}
  DATABASE_POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | b64enc }}
  DATABASE_POSTGRES_DB_NAME: {{ .Values.postgres.auth.database | b64enc }}
  DATABASE_POSTGRES_SSL_MODE: {{ "disable" | b64enc }}
  DATABASE_URL: {{ printf "postgres://%s:%s@%s-postgres:5432/hatchet?sslmode=disable" .Values.postgres.auth.username .Values.postgres.auth.password .Release.Name | b64enc }}
  {{- end }}
  {{- if .Values.rabbitmq.enabled }}
  SERVER_TASKQUEUE_RABBITMQ_URL: {{ "amqp://hatchet:hatchet@hatchet-stack-rabbitmq:5672/" | b64enc }}
  {{- end }}
