apiVersion: v2
name: hatchet-stack
description: A Helm chart for deploying Hatchet on Kubernetes together with a PostgreSQL database and RabbitMQ.
type: application
version: 0.9.2
maintainers:
  - name: Hatchet Engineering
    email: alexander@hatchet.run
dependencies:
  - name: "hatchet-api"
    condition: api.enabled
    repository: "file://../hatchet-api"
    version: "^0.9.2"
    alias: api
  - name: "hatchet-api"
    condition: engine.enabled
    repository: "file://../hatchet-api"
    version: "^0.9.2"
    alias: engine
  - name: "hatchet-frontend"
    condition: frontend.enabled
    repository: "file://../hatchet-frontend"
    version: "^0.9.2"
    alias: frontend

  # https://github.com/bitnami/charts/tree/main/bitnami/postgresql
  - name: "postgresql"
    condition: postgres.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "^16.7.12"
    alias: postgres

  # Postgres Operator - PostgresCluster
  # Docs: https://access.crunchydata.com/documentation/postgres-operator/latest/
  # Chart: https://github.com/jshimko/helm-charts/tree/main/charts/postgrescluster
  - name: postgrescluster
    version: "^5.8.2"
    repository: https://jshimko.github.io/helm-charts
    condition: postgrescluster.enabled

  # https://github.com/bitnami/charts/tree/main/bitnami/rabbitmq
  - name: "rabbitmq"
    condition: rabbitmq.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "^16.0.8"
    alias: rabbitmq
